site_name: Invana Docs
site_author: Ravi Raja Merugu

repo_url: https://github.com/invana/invana-studio
edit_uri: '' #blob/master/docs/
theme:
    name: material
    locale: en
    # analytics: {gtag: 'G-xxxx'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django

extra_css:
    - assets/css/extra.css
    
extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/invana
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/mkdocs-material/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk
copyright: Copyright &copy; 2022 <a href="https://invana.io">Invana</a>, Maintained by the <a href="https://github.com/rrmerugu">Ravi Raja Merugu</a>.


# Configuration
theme:
  name: material
  # custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# # Plugins
# plugins:
#   - search:
#       separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - attr_list
  # - md_in_html
  # - def_list
  # - footnotes
  # - toc:
  #     permalink: true
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed:
  #     alternate_style: true
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde



# Page tree
nav:
  - Home: index.md
  
    # # - Invana Docs: index.md
    # - Introduction:
    #   - What is Invana: introduction/index.md
    # - Installation:
    #   - Invana Engine: introduction/install.md
    #   - Invana Studio: introduction/install.md
    # - About:
    #   - License: about/license.md
    #   - Help and Support: about/help-and-support.md
    #   - Contributing: about/contributing.md
    #   - Release Notes: about/release-notes.md
  - Guides:
    - Introduction: getting-started/index.md
    - Concepts: getting-started/concepts.md
    - Installation methods:
      - Invana Studio : getting-started/install/invana-studio.md
      - Invana Engine : getting-started/install/invana-engine.md      
    - Contributing: getting-started/contributing.md
  - Product Manuals:
    - Invana Engine: manuals/invana-engine/index.md
    - Invana Studio: manuals/invana-studio/index.md
  - Developers Guide: 
    - Creating Connector: developers-guide/creating-connector.md
    - Extending Connector: developers-guide/extending-connector.md
